@localhost=localhost:4004/odata/v4/main
@id=fe27fd5f-452d-43a4-a81d-8ac8c8d3caff
@customerId=dcc9401d-914f-4131-a7a4-15a73ab9954c
@productId=dc078ff0-a5b8-4670-afa5-018afd094154

GET http://{{localhost}}/SalesOrdersHeaders?$filter=id eq {{id}}&$expand=items
Content-Type: application/json

###

POST http://{{localhost}}/SalesOrdersHeaders
Content-Type: application/json

  {
    "id": "{{id}}",
    "customer_id": "{{customerId}}",
    "totalAmount": 10.89,
    "items":[
            { 
              "id": "e5694784-d9cc-432f-bad4-2529167f9587",
              "header_id": "{{id}}",
              "product_id":  "{{productId}}",
              "quantity": 10,
              "price": 2.99
            }
            ]
  }

###

PUT http://{{localhost}}/SalesOrdersHeaders(id={{id}})
Content-Type: application/json

{
    "modifiedBy": "mimi"
}

###

DELETE http://{{localhost}}/SalesOrdersHeaders(id={{id}})
Content-Type: application/json
